# Generated by Django 2.1.1 on 2018-09-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=30)),
                ('rating', models.FloatField()),
                ('review_value', models.IntegerField()),
                ('price', models.FloatField()),
                ('sale', models.IntegerField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('FCN', 'Fiction'), ('ABG', 'Autobiography')], default='NUL', max_length=3)),
                ('ISBN', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
    ]
