# Generated by Django 2.0.5 on 2018-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='delivery_time',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
