# Generated by Django 2.0.5 on 2018-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180923_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/static/deafult_book.gif', upload_to=''),
        ),
    ]
