# Generated by Django 2.0.5 on 2018-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180923_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(default='/static/default_book.gif'),
        ),
    ]
