# Generated by Django 2.0.5 on 2018-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20180923_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1999),
        ),
    ]
