# Generated by Django 2.0.5 on 2018-10-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20180923_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FCN', 'Fiction'), ('ABG', 'Autobiography')], default='NULL', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='review_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, default=1994, null=True),
        ),
    ]
