# Generated by Django 2.0.5 on 2018-10-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20180924_0751'),
        ('book', '0009_auto_20181003_2255'),
    ]

    operations = [
    ]
