# Generated by Django 2.0.5 on 2018-10-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20181003_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
    ]
