# Generated by Django 2.0.5 on 2018-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_merge_20181005_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, default=1994, null=True),
        ),
    ]
