# Generated by Django 2.0.5 on 2018-10-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_description'),
        ('book', '0011_auto_20181005_1616'),
    ]

    operations = [
    ]
